### ISSUE TITLE
InspectorGadgetzan.lua line 333:    attempt to index a nil value

### ISSUE THREAD

**Issue by cyber21tan** [ChrisNolan/InspectorGadgetzan#7]
Date: 2016-08-11 13:02:02
ID: 1
Error occured in: Global
Count: 1
Message: ...ace\AddOns\InspectorGadgetzan\InspectorGadgetzan.lua line 333:
   attempt to index a nil value
Debug:
   (tail call): ?
   ...ace\AddOns\InspectorGadgetzan\InspectorGadgetzan.lua:333: setUpFunction()
   ..\FrameXML\AlertFrames.lua:121: ShowAlert()
   ..\FrameXML\AlertFrames.lua:101: AddAlert()
   ...ace\AddOns\InspectorGadgetzan\InspectorGadgetzan.lua:1274: ?()
   ...een\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...een\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4

   [string "safecall Dispatcher[1]"]:13: ?()
   ...een\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: Fire()
   ...AddOns\AutoVendor\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...AddOns\AutoVendor\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v5.21f.5579 (SanctimoniousSwamprat)
  WowheadLooter, v60014
  Accountant, v6.02.60200
  ACP, v3.4.28 
  AFKfullscreen, v2.0-Release
  AutoVendor, v31
  BadBoy, v13.025
  BadBoyCCleaner, v
  BadBoyGuilded, v
  BagSync, v9.1
  Bazooka, vv2.7.1
  BetterTooltips, vv2.3.1
  Blitz, v6.0
  BrokerEverything, v2.16-Release8
  ClassIcons, v7.2
  DBMArchaeology, v
  DBMCore, v
  DBMDefaultSkin, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DBMVoA, v
  DebugLib, v5.1.DEV.337(/embedded)
  ExplorerCoords, v1.5.2
  FactionAddict, v1.34
  HandyNotes, vv1.4.8
  HandyNotesDirections, v1
  HandyNotesEverShiftingMirror, v1.0.1
  HandyNotesHigherLearning, v6.2.0.4
  HandyNotesLostAndFound, v1
  HandyNotesTreasureHunter, v1
  HandyNotesWellRead, v6.1.0.4
  HandyNotesWorldMapButton, v2.4
  ImprovedOptionsFrames, v1.5.5
  InspectorGadgetzan, v7.0.3.7
  InstanceProfits, v
  LagBar, v3.5
  LeatrixPlus, v7.0.48
  LibExtraTip, v5.12.DEV.390(/embedded)
  LibSharedMedia30, v3.0-93
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.146
  MinimapButtonFrame, v3.1.10e
  MinimapButtonFrameSkinPack, v3.0.1b
  mOnArsWardrobeHelper, v1.13.9
  Overachiever, v0.84
  OverachieverTabs, v0.84
  PassLoot, v4.3
  Pawn, v2.0.7
  Postal, vv3.5.8
  Prat30, v3.6.14  
  Prat30Libraries, v
  RaresTip, vr10
  SavedInstances, v7.0.1
  SignOn, vv2.4.2
  SilverDragon, vv3.2.5
  SimpleGold, v5.5.0
  SlashHelp, v4.2
  Stubby, v5.21f.5579 (SanctimoniousSwamprat)
  TipTac, v16.07.23
  TomTom, vv70000-1.0.0
  TradeSkillInfo, vv2.3.11
  TradeSkillInfoUI, vv2.3.11
  TradeSkillMaster, vv3.4.29
  TradeSkillMasterAccounting, vv3.0.16
  TradeSkillMasterAppHelper, vv3.0.1
  TradeSkillMasterAuctionDB, vv3.1.12
  TradeSkillMasterAuctioning, vv3.0.12
  TradeSkillMasterMailing, vv3.0.11
  WoWTokenWatch, v1.0.3
  XToLevel, v7.0.3_46
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=747)

was in Vault of Archavon when this happened

**Comment by ChrisNolan** [comment]
I believe this was handled in https://github.com/ChrisNolan/InspectorGadgetzan/commit/edd699a5b0d08d62a49cde36bcb4f52d95fbf81a

Thank you for your report, and let me know if it happens again please.
